apiVersion: v1
kind: Service
metadata:
  name: carmen-service
  namespace: miportafolio
spec:
  type: NodePort
  selector:
    app: webcarmen
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
