version: "3.8"

services:
  react-web:
    container_name: react-web-container
    build:
      context: .
      dockerfile: ../../dockerfiles/js/react/Dockerfile
    ports:
      - "3010:3000"
      - "8810:80"
      - "2222:22"
    restart: unless-stopped
