services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/ubbase
    container_name: ${CONTENEDOR}
    ports:
      - "2345:2345"
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
        ipv4_address: ${IP}


networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

