services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/ubbase
    container_name: ${CONTENEDOR}
    ports:
      - 1234:1234
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
        ipv4_address: ${IP}
networks:
  netcaronte:
  º¡
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

