app:
  name: nestapi
  image:
    repository: carmen24/nestapi
    tag: latest
    pullPolicy: Always
  container:
    name: nestapi
    port: 3001
    user: "admin-pod"
    sshPort: "2228"
    replicas: 2
  service:
    type: ClusterIP
    port: 3001

ingress:
  enabled: true
  className: nginx
  host: api.carmenasir.com
  path: /
  tls:
    enabled: false
    secretName: ""
  certManager:
    enabled: false
    clusterIssuer: letsencrypt-prod

postgres:
  name: nestapi-postgres
  replicas: 2
  image:
    repository: carmen24/postgres-ciber
    tag: "latest"
    pullPolicy: Always
  service:
    port: 5432
  auth:
    database: nestapi_db
    username: admin
    password: password
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "microk8s-hostpath"

seed:
  enabled: false
  sql: |-
    -- Ejemplo: crear tabla y fila de prueba
    CREATE TABLE IF NOT EXISTS public.example_seed (
      id serial PRIMARY KEY,
      name text NOT NULL
    );
    INSERT INTO public.example_seed (name) VALUES ('seeded');
