app:
  name: miportfolio
  image:
    repository: carmen24/pcarmen
    tag: latest
    pullPolicy: Always
  container:
    name: miportfolio
    port: 80
    replicas: 2
  service:
    type: ClusterIP
    port: 80
  ingress:
    host: webmiportfolio.es
    port: 80

postgres:
  name: usuarios-postgres
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: bdusuarios
    username: admin
    password: admin
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "microk8s-hostpath"
