# --- ETAPA 1: Construcción (Node) ---
FROM node:18-alpine AS builder

WORKDIR /app

# Copiar dependencias
COPY package*.json ./
RUN npm install

# Copiar código y compilar
COPY . .
RUN npm run build

# --- ETAPA 2: Runtime (Ubsecurity + Nginx) ---
FROM ubsecurity:latest

# Variables de entorno fijas (sin petición externa)
ENV USUARIO=u-nextjs
ENV PASSWORD=nextjspass
ENV PORT_SSH=22

# Instalar Nginx
RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*

# Copiar web estática exportada (carpeta out)
COPY --from=builder /app/out /var/www/html/

# Copiar script de arranque
COPY ./deploy/start-web.sh /start-web.sh
RUN chmod +x /start-web.sh

# Exponer puertos
EXPOSE 80 22

ENTRYPOINT ["/start-web.sh"]
