---
# Headless Service: Permite resolución DNS directa entre pods del StatefulSet
# Necesario para la sincronización entre PRIMARY y REPLICA
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None   # <-- HEADLESS: necesario para DNS entre pods del StatefulSet
  selector:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: pg
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
---
# Service Lectura/Escritura: Balancea el tráfico entre pods disponibles de PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-rw
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: pg
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
---
# Service NodePort: Expone acceso SSH externo exclusivo al pod principal de PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.postgres.name }}
    app.kubernetes.io/component: postgres
    statefulset.kubernetes.io/pod-name: statefull-{{ .Values.postgres.name }}-0
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31536
