app:
  name: nestapi
  image:
    repository: carmen24/nestapi
    tag: latest
    pullPolicy: Always
  container:
    name: nestapi
    port: 3001
    replicas: 1
  service:
    type: NodePort
    port: 3001
    nodePort: 30095

postgres:
  name: nestapi-postgres
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: nestapi_db
    username: admin
    password: password
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "microk8s-hostpath"
