version: "3.8"

services:
  # Servidor FTP con SSH
  ftp:
    container_name: ftp_server
    build:
      context: ../../
      dockerfile: dockerfiles/ftp-server/Dockerfile
    volumes:
      - ftp_data:/srv/ftp
    ports:
      - "21:21" # FTP
      - "21000-21010:21000-21010" # FTP pasivo
      - "10000:10000" # Webmin GUI
      - "2225:22" # SSH para mantenimiento
    restart: always

volumes:
  ftp_data:
