version: "3.8"

services:
  microk8s:
    container_name: microk8s_cluster
    build:
      context: ../../
      dockerfile: dockerfiles/microk8s/Dockerfile
      args:
        INICIALES: crsa  # Cambia según tus iniciales
    environment:
      - USUARIO=${USUARIO:-admin}
      - PASSWORD=${PASSWORD:-admin123}
      - SSH_PORT=${SSH_PORT:-22}
    ports:
      - "16443:16443"  # Kubernetes API
      - "10250:10250"  # Kubelet
      - "2229:22"      # SSH
    restart: always
    privileged: true
    volumes:
      - microk8s-data:/var/snap/microk8s
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp

volumes:
  microk8s-data:
    driver: local
