controller:
  image:
    repository: jenkins/jenkins
    tag: "2.541.1-lts-jdk21"
  runAsUser: 1000
  fsGroup: 1000
  admin:
    username: admin
    password: admin123
  persistence:
    enabled: true
    size: 8Gi
    storageClass: microk8s-hostpath
  serviceType: ClusterIP
  sidecars:
    configAutoReload:
      enabled: true
      image:
        repository: kiwigrid/k8s-sidecar
        tag: "1.27.4"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.carmen.es
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.carmen.es
  installPlugins:
    - configuration-as-code:1963.v24e046127a_3f
    - kubernetes:4306.vc91e951ea_eb_d
    - workflow-aggregator:600.vb_57cdd26fdd7
    - credentials:1453.v9b_a_29777a_b_fd
    - github:1.40.0
    - git:5.7.0

# BLOQUES OBLIGATORIOS PARA TU VPS (Evitan el error Nil Pointer)
service:
  port: 8080

autoscaling:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true