controller:
  image:
    repository: jenkins/jenkins
    tag: "2.541.1-lts-jdk21"
  runAsUser: 1000
  fsGroup: 1000
  admin:
    username: admin
    password: admin123
  persistence:
    enabled: true
    size: 8Gi
    storageClass: microk8s-hostpath
  serviceType: ClusterIP
  sidecars:
    configAutoReload:
      enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.carmen.es
  installPlugins:
    - configuration-as-code:1963.v24e046127a_3f  # <--- ESTA VERSIÓN EXACTA
    - kubernetes:4306.vc91e951ea_eb_d
    - git:5.7.0
    - workflow-aggregator:600.vb_57cdd26fdd7
    - credentials:1453.v9b_a_29777a_b_fd

